<?php $_items_count = Mage::helper('checkout/cart')->getItemsCount(); ?>
<div class="header-cart col-md-2">
    <div class="cart-heading">
        <a href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>" class="title">
            <?php echo $this->getCartTitle(); ?>
        </a>
        <span class="amount">
            <?php echo Mage::helper('core')->currency($this->getSubtotal(true), true, false); ?>
        </span>
    </div>
    <div id="headercart-items"></div>
</div>
<?php if ($_items_count > 0): ?>
    <script type="text/javascript">
        var headerCart = {
            target: null,
            state: 'hidden',
            response: null,
            getItems: function () {
                var target = this.getTarget();
                if (target) {
                    var self = this;
                    jQuery.post("<?php echo Mage::getBaseUrl() ?>header-cart", function (data) {
                        self.response = data;
                        target.html(self.response);
                    });
                }
            },
            showItems: function () {
                if (this.state == 'hidden') {
                    if (!this.response) {
                        this.getItems();
                    }
                    this.getTarget().show().addClass('visible');
                    this.state = 'visible';
                }
            },
            hideItems: function () {
                if (this.state == 'visible')
                {
                    this.getTarget().hide().removeClass('visible');
                    this.state = 'hidden';
                }
            },
            getTarget: function ()
            {
                if (!this.target) {
                    this.target = jQuery('#headercart-items');
                }
                return this.target;
            }
        }

        jQuery(document).ready(function () {
            jQuery('.header-cart').hover(function () {
                headerCart.showItems();
            }, function () {
                headerCart.hideItems();
            });
        });

    </script>
<?php endif; ?>
