<?php $_items_count = Mage::helper('checkout/cart')->getItemsCount(); ?>
<div class="header-cart">
    <div class="cart-heading">
        <a href="<?php echo Mage::helper('checkout/url')->getCartUrl(); ?>" class="title go-to-cart">
            <?php echo $this->getCartTitle(); ?>
        </a>
        <a href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl(); ?>" class="go-to-checkout">
            <?php echo $this->__('Go To Checkout'); ?>
        </a>
        <?php if ($this->getSummaryCount() > 0): ?>
            <span class="items"><?php echo $this->getSummaryCount(); ?></span>
        <?php endif; ?>
    </div>
    <div id="headercart-items"></div>
</div>
<?php if ($_items_count > 0): ?>
    <script type="text/javascript">
        var headerCart = {
            target: null,
            state: 'hidden',
            getItems: function () {
                var target = this.getTarget();
                if (target) {
                    jQuery.post("<?php echo Mage::getBaseUrl() ?>header-cart", function (data) {
                        target.html(data);
                    });
                }
            },
            showItems: function () {
                if (this.state == 'hidden') {
                    this.getItems();
                    this.getTarget().show().addClass('visible');
                    this.state = 'visible';
                }
            },
            hideItems: function () {
                if (this.state == 'visible')
                {
                    this.getTarget().hide().removeClass('visible');
                    this.state = 'hidden';
                }
            },
            getTarget: function ()
            {
                if (this.target) {
                    return this.target;
                } else {
                    return jQuery('#headercart-items');
                }
            }
        }

        jQuery(document).ready(function () {
            jQuery('.header-cart').hover(function () {
                headerCart.showItems();
            }, function () {
                headerCart.hideItems();
            });
        });
    </script>
<?php endif; ?>
