<?php $_items = $this->getRecentItems(); ?>
<ul>
    <?php foreach ($_items as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach; ?>
</ul>
<?php if ($this->getRemainingItemsCount() > 0): ?>
<div class="headercart-remaining">
    <span class="label">
        <?php if (Mage::getStoreConfig('checkout/cart_link/use_qty')): ?>
            <?php if ($this->getRemainingItemsCount() == 1): ?>
                <?php echo $this->__('%s other item', $this->getRemainingItemsCount()); ?>
            <?php else: ?>
                <?php echo $this->__('%s other items', $this->getRemainingItemsCount()); ?>
            <?php endif; ?>
        <?php else: ?>
            <?php if ($this->getRemainingItemsCount() == 1): ?>
                <?php echo $this->__('%s other article', $this->getRemainingItemsCount()); ?>
            <?php else: ?>
                <?php echo $this->__('%s other articles', $this->getRemainingItemsCount()); ?>
            <?php endif; ?>
        <?php endif; ?>
    </span>
    <span class="value">
        <?php echo Mage::helper('core')->currency($this->getRemainingItemsSubtotal(true), true, false); ?>
    </span>
</div>
<?php endif; ?>
<div class="headercart-totals">
    <span class="label"><?php echo $this->__('Subtotal:')?></span>
    <span class="value">
        <?php echo Mage::helper('core')->currency($this->getSubtotal(true), true, false); ?>
    </span>
</div>
<div class="actions">
    <a href="<?php echo Mage::getUrl('checkout/cart'); ?>" class="show-cart-link" ><span><?php echo $this->__('Go To Cart') ?></span></a>
    <a href="<?php echo Mage::getUrl('checkout/onepage'); ?>" class="proceed-checkout-link"><span><?php echo $this->__('Go To Checkout') ?></span></a>
</div>
